name: manim-binder-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - manim
  - numpy
  - scipy
  - matplotlib
  - ipykernel
  - jupyterlab
  - pip
  - pip:
    - manim-jupyter
